name: security-pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  codeql:
    name: CodeQL (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  npm-audit-vuln:
    name: npm audit (vuln) — expect FAIL on High
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./vuln } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm i
      - run: npm audit --omit=dev --audit-level=high

  npm-audit-secure:
    name: npm audit (secure) — expect PASS
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./secure } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm i
      - run: npm audit --omit=dev --audit-level=high

  zap-juice-shop:
    name: ZAP Baseline vs Juice Shop — expect FAIL
    runs-on: ubuntu-latest
    services:
      juice:
        image: bkimminich/juice-shop
        ports: ["3000:3000"]
    steps:
      - uses: actions/checkout@v4

      - name: Wait for Juice Shop
        run: |
          for i in {1..60}; do
            curl -fsS http://127.0.0.1:3000 >/dev/null && exit 0
            sleep 2
          done
          echo "Juice Shop never became ready" >&2
          exit 1

      - name: Pull ZAP image
        run: docker pull owasp/zap2docker-stable

      - name: ZAP Baseline (Juice Shop)
        run: |
          docker run --rm --network=host \
            -v "$PWD":/zap/wrk -w /zap/wrk -u 0:0 \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://127.0.0.1:3000 -a -l High -m 3 \
            -r zap-report-juice-shop.html

      - name: Upload ZAP report (Juice Shop)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report-juice-shop
          path: zap-report-juice-shop.html

  zap-secure:
    name: ZAP Baseline vs Secure App — expect PASS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        working-directory: ./secure
        run: npm i

      - name: Start app
        working-directory: ./secure
        run: |
          nohup npm start &
          sleep 3

      - name: Wait for Secure App
        run: |
          for i in {1..60}; do
            curl -fsS http://127.0.0.1:4000 >/dev/null && exit 0
            sleep 2
          done
          echo "Secure app never became ready" >&2
          exit 1

      - name: Pull ZAP image
        run: docker pull owasp/zap2docker-stable

      - name: ZAP Baseline (Secure)
        run: |
          docker run --rm --network=host \
            -v "$PWD":/zap/wrk -w /zap/wrk -u 0:0 \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://127.0.0.1:4000 -a -l High -m 3 \
            -r zap-report-secure.html

      - name: Upload ZAP report (Secure)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report-secure
          path: zap-report-secure.html
