name: security-pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  npm-audit-vuln:
    name: npm audit (vuln) — expect FAIL on High
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./vuln } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm i
      - run: npm audit --omit=dev --audit-level=high

  npm-audit-secure:
    name: npm audit (secure) — expect PASS
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./secure } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm i
      - run: npm audit --omit=dev --audit-level=high

  zap-juice-shop:
    name: ZAP Baseline vs Juice Shop — expect FAIL
    runs-on: ubuntu-latest
    services:
      juice:
        image: bkimminich/juice-shop
        ports: ["3000:3000"]
    steps:
      - uses: actions/checkout@v4

      # Wait until Juice Shop is reachable on the runner's localhost:3000
      - name: Wait for Juice Shop
        run: |
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:3000 >/dev/null; then
              echo "Juice Shop is up"; exit 0
            fi
            sleep 2
          done
          echo "Juice Shop never became ready" >&2
          exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://127.0.0.1:3000'
          fail_action: true
          cmd_options: '-a -l High -m 3'
          additional_docker_options: '--network=host'

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-juice-shop
          path: report_html.html

  zap-secure:
    name: ZAP Baseline vs Secure App — expect PASS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        working-directory: ./secure
        run: npm i

      - name: Start app
        working-directory: ./secure
        run: |
          nohup npm start &
          # give Node time to boot
          sleep 2

      - name: Wait for Secure App
        run: |
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:4000 >/dev/null; then
              echo "Secure app is up"; exit 0
            fi
            sleep 2
          done
          echo "Secure app never became ready" >&2
          exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://127.0.0.1:4000'
          fail_action: true
          cmd_options: '-a -l High -m 3'
          additional_docker_options: '--network=host'

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-secure
          path: report_html.html
